///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace wfrmhr
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenBrowser recording.
    /// </summary>
    [TestModule("ecdc309c-4bd7-4bf2-9ef0-3dbc24856bf0", ModuleType.Recording, 1)]
    public partial class OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the wfrmhrRepository repository.
        /// </summary>
        public static wfrmhrRepository repo = wfrmhrRepository.Instance;

        static OpenBrowser instance = new OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://d1wfapps.vividsolutions.com/pub/wfrm-resources' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://d1wfapps.vividsolutions.com/pub/wfrm-resources", "chrome", "", false, false, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebADEDeveloperLogon.UserSelect' at 184;10.", repo.WebADEDeveloperLogon.UserSelectInfo, new RecordItemIndex(1));
            repo.WebADEDeveloperLogon.UserSelect.Click("184;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebADEDeveloperLogonGoogleChrome' at 1150;590.", repo.WebADEDeveloperLogonGoogleChrome.SelfInfo, new RecordItemIndex(2));
            repo.WebADEDeveloperLogonGoogleChrome.Self.MoveTo("1150;590");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebADEDeveloperLogonGoogleChrome' at 1154;836.", repo.WebADEDeveloperLogonGoogleChrome.SelfInfo, new RecordItemIndex(3));
            repo.WebADEDeveloperLogonGoogleChrome.Self.MoveTo("1154;836");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LWin down}' with focus on 'WebADEDeveloperLogon.UserSelect'.", repo.WebADEDeveloperLogon.UserSelectInfo, new RecordItemIndex(4));
            repo.WebADEDeveloperLogon.UserSelect.PressKeys("{LWin down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebADEDeveloperLogonGoogleChrome' at 677;846.", repo.WebADEDeveloperLogonGoogleChrome.SelfInfo, new RecordItemIndex(5));
            repo.WebADEDeveloperLogonGoogleChrome.Self.Click("677;846");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}{LWin up}' with focus on 'WebADEDeveloperLogonGoogleChrome'.", repo.WebADEDeveloperLogonGoogleChrome.SelfInfo, new RecordItemIndex(6));
            repo.WebADEDeveloperLogonGoogleChrome.Self.PressKeys("{LControlKey up}{LWin up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebADEDeveloperLogon.UserSelect' at 129;14.", repo.WebADEDeveloperLogon.UserSelectInfo, new RecordItemIndex(7));
            repo.WebADEDeveloperLogon.UserSelect.Click("129;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebADEDeveloperLogon.UserSelect' at 119;12.", repo.WebADEDeveloperLogon.UserSelectInfo, new RecordItemIndex(8));
            repo.WebADEDeveloperLogon.UserSelect.Click("119;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebADEDeveloperLogon.Submit' at 33;19.", repo.WebADEDeveloperLogon.SubmitInfo, new RecordItemIndex(9));
            repo.WebADEDeveloperLogon.Submit.Click("33;19");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
