///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace wfrmhr
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VehicleAndAccomodationDetails recording.
    /// </summary>
    [TestModule("68b800d0-0566-4a61-ae81-3ee4280a3e47", ModuleType.Recording, 1)]
    public partial class VehicleAndAccomodationDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the wfrmhrRepository repository.
        /// </summary>
        public static wfrmhrRepository repo = wfrmhrRepository.Instance;

        static VehicleAndAccomodationDetails instance = new VehicleAndAccomodationDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VehicleAndAccomodationDetails()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VehicleAndAccomodationDetails Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsD1wfappsVividsolutionsComPub' at 42;20.", repo.ApplicationUnderTest.HttpsD1wfappsVividsolutionsComPubInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HttpsD1wfappsVividsolutionsComPub.Click("42;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CdkCellCdkColumnNameMatCellMatCo' at 58;26.", repo.ApplicationUnderTest.CdkCellCdkColumnNameMatCellMatCoInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.CdkCellCdkColumnNameMatCellMatCo.Click("58;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RaptorsII' at 82;15.", repo.ApplicationUnderTest.RaptorsIIInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RaptorsII.Click("82;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CdkGlobalOverlayWrapper.MatRadioOuterCircle' at 6;10.", repo.ApplicationUnderTest.CdkGlobalOverlayWrapper.MatRadioOuterCircleInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.CdkGlobalOverlayWrapper.MatRadioOuterCircle.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CdkGlobalOverlayWrapper.Text' at 43;11.", repo.ApplicationUnderTest.CdkGlobalOverlayWrapper.TextInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.CdkGlobalOverlayWrapper.Text.Click("43;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
