///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace wfrmhr
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the wfrmhrRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("90584611-5862-417c-b693-c9003ea6109c")]
    public partial class wfrmhrRepository : RepoGenBaseFolder
    {
        static wfrmhrRepository instance = new wfrmhrRepository();
        wfrmhrRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the wfrmhrRepository element repository.
        /// </summary>
        [RepositoryFolder("90584611-5862-417c-b693-c9003ea6109c")]
        public static wfrmhrRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public wfrmhrRepository() 
            : base("wfrmhrRepository", "/", null, 0, false, "90584611-5862-417c-b693-c9003ea6109c", ".\\RepositoryImages\\wfrmhrRepository90584611.rximgres")
        {
            _applicationundertest = new wfrmhrRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("90584611-5862-417c-b693-c9003ea6109c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a75dfc80-d9e3-495d-b2a9-4fba3120ed8b")]
        public virtual wfrmhrRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class wfrmhrRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a75dfc80-d9e3-495d-b2a9-4fba3120ed8b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            wfrmhrRepositoryFolders.CdkGlobalOverlayWrapperFolder _cdkglobaloverlaywrapper;
            RepoItemInfo _httpsd1wfappsvividsolutionscompubInfo;
            RepoItemInfo _cdkcellcdkcolumnnamematcellmatcoInfo;
            RepoItemInfo _raptorsiiInfo;
            RepoItemInfo _spantagcancelInfo;
            RepoItemInfo _assignmentsInfo;
            RepoItemInfo _centreInfo;
            RepoItemInfo _ruchitestmanifestInfo;
            RepoItemInfo _matradiooutercircleInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='d1wfapps.vividsolutions.com']", parentFolder, 30000, null, false, "a75dfc80-d9e3-495d-b2a9-4fba3120ed8b", "")
            {
                _cdkglobaloverlaywrapper = new wfrmhrRepositoryFolders.CdkGlobalOverlayWrapperFolder(this);
                _httpsd1wfappsvividsolutionscompubInfo = new RepoItemInfo(this, "HttpsD1wfappsVividsolutionsComPub", ".//div[#'wfrmMain']/?/?/tag[@tagname='wf-application']/div[2]/div[3]/tag/div[2]/div/a[3]", ".//div[#'wfrmMain']//tag[@tagname='wf-menu']/div[2]/div/a[3]", 30000, null, "9b84029e-17c5-43a3-8989-b66976745059");
                _cdkcellcdkcolumnnamematcellmatcoInfo = new RepoItemInfo(this, "CdkCellCdkColumnNameMatCellMatCo", ".//div[#'core-interface-container']//tag[@tagname='base-wrapper']/div/div/div/div[4]/table/tbody/tr[1]/td[2]", ".//div[#'core-interface-container']//tbody/tr[1]/td[2]", 30000, null, "3ed16c87-ee8d-4801-831d-98b916c06940");
                _raptorsiiInfo = new RepoItemInfo(this, "RaptorsII", ".//div[#'core-interface-container']/div//tag[@tagname='base-wrapper']/div/div/div[2]/tag[@tagname='mat-tab-group']/div/tag[1]/div/?/?/tag[@tagname='wfrm-assignment-detail-sections']/div//tag[@tagname='wfrm-assignment-detail-resources-desktop']/tag[@tagname='wfrm-base-expansion-panel']/tag[@tagname='mat-expansion-panel']/div/div/div/div/div/div[2]/div/table/tbody/tr[2]/td[@innertext='Raptors II']", ".//div[#'core-interface-container']//td[@innertext='Raptors II']", 30000, null, "a2792ee2-a664-4dde-a052-c367114fb497");
                _spantagcancelInfo = new RepoItemInfo(this, "SpanTagCancel", "body/div[5]/div[5]/?/?/tag[@tagname='owl-date-time-container']/div[2]/div[2]/button[1]/span[@innertext=' Cancel ']", ".//span[@innertext=' Cancel ']", 30000, null, "38e241c6-b8cf-4247-bfc4-d282b0239541");
                _assignmentsInfo = new RepoItemInfo(this, "Assignments", ".//div[#'wfrmMain']/?/?/tag[@tagname='wf-application']/div[2]/div[3]/tag/div[2]/div/a[3]/span[@innertext='Assignments']", ".//div[#'wfrmMain']//span[@innertext='Assignments']", 30000, null, "e756ede4-32d2-4bcb-a6c2-cd68d21ab46f");
                _centreInfo = new RepoItemInfo(this, "Centre", ".//div[#'core-interface-container']//tag[@tagname='base-wrapper']/div/div/div/div[4]/table/tbody/tr[1]/td[1]/span[@innertext='Centre']", ".//div[#'core-interface-container']//tbody/tr[1]/td[1]/span[@innertext='Centre']", 30000, null, "67186c17-4f64-4e47-a60f-521a0525a0c8");
                _ruchitestmanifestInfo = new RepoItemInfo(this, "RuchiTestManifest", ".//div[#'core-interface-container']/div//tag[@tagname='base-wrapper']/div/div/div[2]/tag[@tagname='mat-tab-group']/div/tag[1]/div/?/?/tag[@tagname='wfrm-assignment-detail-sections']/div//tag[@tagname='wfrm-assignment-detail-resources-desktop']/tag[@tagname='wfrm-base-expansion-panel']/tag[@tagname='mat-expansion-panel']/div/div/div/div/div/div[2]/div/table/tbody/tr[1]/td[@innertext='Ruchi Test Manifest']", ".//div[#'core-interface-container']//td[@innertext='Ruchi Test Manifest']", 30000, null, "f2adb0d5-31db-4bc8-9baf-ac0af45d0089");
                _matradiooutercircleInfo = new RepoItemInfo(this, "MatRadioOuterCircle", "body/div[5]/div[4]//tag[@tagname='wfrm-base-dialog']/div[2]/div[1]/tag[@tagname='mat-tab-group']/div/tag[1]/div/div/div/div[1]/?/?/tag[@tagname='mat-form-field']/div/div[1]/?/?/tag[@tagname='mat-radio-group']/tag[2]/label/span[1]/span[1]", ".//tag[@tagname='mat-radio-group']/tag[2]/label/span[1]/span[1]", 30000, null, "0234fdd1-c4b4-4ced-97c7-5a537e4475b2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a75dfc80-d9e3-495d-b2a9-4fba3120ed8b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a75dfc80-d9e3-495d-b2a9-4fba3120ed8b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsD1wfappsVividsolutionsComPub item.
            /// </summary>
            [RepositoryItem("9b84029e-17c5-43a3-8989-b66976745059")]
            public virtual Ranorex.ATag HttpsD1wfappsVividsolutionsComPub
            {
                get
                {
                    return _httpsd1wfappsvividsolutionscompubInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsD1wfappsVividsolutionsComPub item info.
            /// </summary>
            [RepositoryItemInfo("9b84029e-17c5-43a3-8989-b66976745059")]
            public virtual RepoItemInfo HttpsD1wfappsVividsolutionsComPubInfo
            {
                get
                {
                    return _httpsd1wfappsvividsolutionscompubInfo;
                }
            }

            /// <summary>
            /// The CdkCellCdkColumnNameMatCellMatCo item.
            /// </summary>
            [RepositoryItem("3ed16c87-ee8d-4801-831d-98b916c06940")]
            public virtual Ranorex.TdTag CdkCellCdkColumnNameMatCellMatCo
            {
                get
                {
                    return _cdkcellcdkcolumnnamematcellmatcoInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The CdkCellCdkColumnNameMatCellMatCo item info.
            /// </summary>
            [RepositoryItemInfo("3ed16c87-ee8d-4801-831d-98b916c06940")]
            public virtual RepoItemInfo CdkCellCdkColumnNameMatCellMatCoInfo
            {
                get
                {
                    return _cdkcellcdkcolumnnamematcellmatcoInfo;
                }
            }

            /// <summary>
            /// The RaptorsII item.
            /// </summary>
            [RepositoryItem("a2792ee2-a664-4dde-a052-c367114fb497")]
            public virtual Ranorex.TdTag RaptorsII
            {
                get
                {
                    return _raptorsiiInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The RaptorsII item info.
            /// </summary>
            [RepositoryItemInfo("a2792ee2-a664-4dde-a052-c367114fb497")]
            public virtual RepoItemInfo RaptorsIIInfo
            {
                get
                {
                    return _raptorsiiInfo;
                }
            }

            /// <summary>
            /// The SpanTagCancel item.
            /// </summary>
            [RepositoryItem("38e241c6-b8cf-4247-bfc4-d282b0239541")]
            public virtual Ranorex.SpanTag SpanTagCancel
            {
                get
                {
                    return _spantagcancelInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagCancel item info.
            /// </summary>
            [RepositoryItemInfo("38e241c6-b8cf-4247-bfc4-d282b0239541")]
            public virtual RepoItemInfo SpanTagCancelInfo
            {
                get
                {
                    return _spantagcancelInfo;
                }
            }

            /// <summary>
            /// The Assignments item.
            /// </summary>
            [RepositoryItem("e756ede4-32d2-4bcb-a6c2-cd68d21ab46f")]
            public virtual Ranorex.SpanTag Assignments
            {
                get
                {
                    return _assignmentsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Assignments item info.
            /// </summary>
            [RepositoryItemInfo("e756ede4-32d2-4bcb-a6c2-cd68d21ab46f")]
            public virtual RepoItemInfo AssignmentsInfo
            {
                get
                {
                    return _assignmentsInfo;
                }
            }

            /// <summary>
            /// The Centre item.
            /// </summary>
            [RepositoryItem("67186c17-4f64-4e47-a60f-521a0525a0c8")]
            public virtual Ranorex.SpanTag Centre
            {
                get
                {
                    return _centreInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Centre item info.
            /// </summary>
            [RepositoryItemInfo("67186c17-4f64-4e47-a60f-521a0525a0c8")]
            public virtual RepoItemInfo CentreInfo
            {
                get
                {
                    return _centreInfo;
                }
            }

            /// <summary>
            /// The RuchiTestManifest item.
            /// </summary>
            [RepositoryItem("f2adb0d5-31db-4bc8-9baf-ac0af45d0089")]
            public virtual Ranorex.TdTag RuchiTestManifest
            {
                get
                {
                    return _ruchitestmanifestInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The RuchiTestManifest item info.
            /// </summary>
            [RepositoryItemInfo("f2adb0d5-31db-4bc8-9baf-ac0af45d0089")]
            public virtual RepoItemInfo RuchiTestManifestInfo
            {
                get
                {
                    return _ruchitestmanifestInfo;
                }
            }

            /// <summary>
            /// The MatRadioOuterCircle item.
            /// </summary>
            [RepositoryItem("0234fdd1-c4b4-4ced-97c7-5a537e4475b2")]
            public virtual Ranorex.SpanTag MatRadioOuterCircle
            {
                get
                {
                    return _matradiooutercircleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MatRadioOuterCircle item info.
            /// </summary>
            [RepositoryItemInfo("0234fdd1-c4b4-4ced-97c7-5a537e4475b2")]
            public virtual RepoItemInfo MatRadioOuterCircleInfo
            {
                get
                {
                    return _matradiooutercircleInfo;
                }
            }

            /// <summary>
            /// The CdkGlobalOverlayWrapper folder.
            /// </summary>
            [RepositoryFolder("b157edf8-289c-4dbb-acfc-366af3c78a3b")]
            public virtual wfrmhrRepositoryFolders.CdkGlobalOverlayWrapperFolder CdkGlobalOverlayWrapper
            {
                get { return _cdkglobaloverlaywrapper; }
            }
        }

        /// <summary>
        /// The CdkGlobalOverlayWrapperFolder folder.
        /// </summary>
        [RepositoryFolder("b157edf8-289c-4dbb-acfc-366af3c78a3b")]
        public partial class CdkGlobalOverlayWrapperFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _falseInfo;
            RepoItemInfo _matradiooutercircleInfo;

            /// <summary>
            /// Creates a new CdkGlobalOverlayWrapper  folder.
            /// </summary>
            public CdkGlobalOverlayWrapperFolder(RepoGenBaseFolder parentFolder) :
                    base("CdkGlobalOverlayWrapper", "body/div[5]/div[3]", parentFolder, 30000, null, false, "b157edf8-289c-4dbb-acfc-366af3c78a3b", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", ".//tag[@tagname='wfrm-base-dialog']/div[2]/div[1]/tag[@tagname='mat-tab-group']/div/tag[1]/div/div/div/div[3]/div[2]/tag/div/div[1]/div/div/input[2]", "tag[1]/div/div/div/div[3]/div[2]/tag[@tagname='mat-form-field']/div/div[1]/div/div/input[2]", 30000, null, "58fd4861-98b3-49b2-b439-eefb8794a13b");
                _falseInfo = new RepoItemInfo(this, "False", ".//tag[@tagname='wfrm-base-dialog']/div[2]/div[1]/tag[@tagname='mat-tab-group']/div/tag[1]/div/div/div/div[4]/div[2]/tag/div/div[1]/?/?/textarea[@required='False']", "tag[1]/div/div/div/div[4]/div[2]/tag[@tagname='mat-form-field']/div/div[1]/div/textarea[@required='False']", 30000, null, "238d4119-0da4-4cb1-b25f-c8f42dd444ce");
                _matradiooutercircleInfo = new RepoItemInfo(this, "MatRadioOuterCircle", "div//tag[@tagname='wfrm-base-dialog']/div[2]/div[1]/tag[@tagname='mat-tab-group']/div/tag[1]/div/div/div/div/div/tag/div/div[1]/div/tag[@tagname='mat-radio-group']/tag[2]/label/span[1]/span[1]", "label/span[1]/span[1]", 30000, null, "d39a867a-d5e1-4a6d-9ad2-95ff07e1321a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b157edf8-289c-4dbb-acfc-366af3c78a3b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b157edf8-289c-4dbb-acfc-366af3c78a3b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("58fd4861-98b3-49b2-b439-eefb8794a13b")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("58fd4861-98b3-49b2-b439-eefb8794a13b")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The False item.
            /// </summary>
            [RepositoryItem("238d4119-0da4-4cb1-b25f-c8f42dd444ce")]
            public virtual Ranorex.TextAreaTag False
            {
                get
                {
                    return _falseInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The False item info.
            /// </summary>
            [RepositoryItemInfo("238d4119-0da4-4cb1-b25f-c8f42dd444ce")]
            public virtual RepoItemInfo FalseInfo
            {
                get
                {
                    return _falseInfo;
                }
            }

            /// <summary>
            /// The MatRadioOuterCircle item.
            /// </summary>
            [RepositoryItem("d39a867a-d5e1-4a6d-9ad2-95ff07e1321a")]
            public virtual Ranorex.SpanTag MatRadioOuterCircle
            {
                get
                {
                    return _matradiooutercircleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MatRadioOuterCircle item info.
            /// </summary>
            [RepositoryItemInfo("d39a867a-d5e1-4a6d-9ad2-95ff07e1321a")]
            public virtual RepoItemInfo MatRadioOuterCircleInfo
            {
                get
                {
                    return _matradiooutercircleInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
